# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: src/BasketAPI/Dockerfile
    ports:
      - 5150:5150
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
