# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  basketapi:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/BasketAPI/Dockerfile
    ports:
      - 5150:5150

  orderingapi:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/OrderingAPI/Dockerfile

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/OrderingAPI/Dockerfile
  healthwebstatus:
    image: ${DOCKER_REGISTRY-}healthwebstatus
    build:
      context: .
      dockerfile: src/HealthWebstatus/Dockerfile

