version: '3.4'

services:
  catalogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  orderingapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  healthwebstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

